diary/diary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary_app/',  include('diary_app.urls')),
    path('', include('diary_app.portfolio_urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/diary_app/urls.py
from django.urls import path
from .import views
from. views import ReflectionListView

app_name = 'diary_app'

urlpatterns = [
    # path('', views.portfolio, name='portfolio'),
    path('regist/', views.regist, name='regist'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('reflection/<int:year>/<int:month>/', ReflectionListView.as_view(), name='reflection'),
    path('my_page/', views.my_page, name='my_page'),
    path('change_password/', views.change_password, name='change_password'),
    path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    path('today_input/<int:year>/<int:month>/<int:day>/', views.today_input, name='today_input'),
    # path('diary_inspection/<int:year>/<int:month>/<int:day>/', DiaryInspectionListView.as_view(), name='diary_inspection'),
    path('edit_diary/<int:pk>/<int:year>/<int:month>/<int:day>/', views.edit_diary, name='edit_diary'),
    path('delete_diary/<int:pk>/<int:year>/<int:month>/<int:day>/', views.delete_diary, name='delete_diary'),
    path('edit_reflection/<int:year>/<int:month>/', views.edit_reflection, name='edit_reflection'),
    path('delete_reflection/<int:year>/<int:month>/', views.delete_reflection, name='delete_reflection'),
    
    
]

diary/templates/user/activate_user.html
{% extends 'user/user_base.html' %}
{% block content%}
{% if messages %}
    {% for message in messages %}
    <div>{{ message.message }}: {{ message.tags }}</div>
    {% endfor %}
{% endif %}
<form method="POST">
    {% csrf_token %}
    {{ activate_form.as_p }}
    <input type="submit" value="ユーザーを有効化する">
</form>    
{% endblock %}

diary/templates/user/registration.html
{% extends 'user/user_base.html' %}
{% block content %}

<style>
body {
  margin: 0;
  height: 100vh;
  display: flex;
  align-items: center;  
  justify-content: center;  
  background-color: #E0FFFF;  
  padding-bottom: 30px;  
}

.form-container {
  width: 400px;
  padding: 30px;
  background-color: white;
  border-radius: 8px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  text-align: center;
}

.form-title {
  font-size: 1.5rem;
  font-weight: bold;
  margin-bottom: 20px;
}

.message-container {
  margin-bottom: 10px;
  color: red;
}

input[type="submit"] {
  width: 100%;
  margin-top: 20px;
}

nav {
  margin-top: 20px;
}

  
input[type="text"], input[type="password"], input[type="email"] {
  width: 100%;
  padding: 12px 16px;
  margin-bottom: 10px;
  box-sizing: border-box;
  border: 1px solid #ccc;
  border-radius: 8px;
  font-size: 18px;
  line-height: 1.4;
  box-shadow: inset 0 1px 3px rgba(0,0,0,0.1);
}


label {
  display: block;
  font-weight: bold;
  margin-bottom: 5px;
}

.form-group {
  margin-bottom: 15px;
  text-align: left;
}

</style>

<div class="form-container">
 <div class="form-title">新規登録</div>
<form method="POST">
    {% csrf_token %}
    <div class="form-group text-start mb-3">
      <label for="{{ regist_form.username.id_for_label }}">名前</label>
      {{ regist_form.username }}
      {% if regist_form.username.errors %}
        <div class="text-danger">{{ regist_form.username.errors }}</div>
      {% endif %}
   </div>

   <div class="form-group text-start mb-3">
      <label for="{{ regist_form.email.id_for_label }}">メールアドレス</label>
      {{ regist_form.email }}
      {% if regist_form.email.errors %}
        <div class="text-danger">{{ regist_form.email.errors }}</div>
      {% endif %}
   </div>

   <div class="form-group text-start mb-3">
      <label for="{{ regist_form.password.id_for_label }}">パスワード</label>
      {{ regist_form.password }}
      {% if regist_form.password.errors %}
        <div class="text-danger">{{ regist_form.password.errors }}</div>
      {% endif %}
   </div>

   <div class="form-group text-start mb-3">
      <label for="{{ regist_form.confirm_password.id_for_label }}">パスワード再入力</label>
      {{ regist_form.confirm_password }}
      {% if regist_form.confirm_password.errors %}
        <div class="text-danger">{{ regist_form.confirm_password.errors }}</div>
      {% endif %}
   </div>

    <input type="submit" value="登録" class="btn btn-primary">
</form>
<nav>
<a href="{% url 'diary_app:login' %}">ログインに戻る</a>
</nav>
{% endblock %}

diary/templates/user/user_base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>
    </head>    
    <body>
       
        <div> 
            {% block content %}
            {% endblock %}
        </div> 
    </div>  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> 
    </body>       
</html>

diary/templates/user/user_login.html
{% extends "user/user_base.html" %}
{% block content %}

<style>
  
  body {
    margin: 0;
    height: 100vh;
    display: flex;
    align-items: center;  
    justify-content: center;  
    background-color: #E0FFFF; 
    padding-bottom: 30px;   
  }

  .form-container {
    width: 400px;
    padding: 30px;
    background-color: white;
    border-radius: 8px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    text-align: center;
  }

  .form-title {
    font-size: 1.5rem;
    font-weight: bold;
    margin-bottom: 20px;
  }

  .message-container {
    margin-bottom: 10px;
    color: red;
    
  }

  input[type="submit"] {
    width: 100%;
    margin-top: 20px;
  }

  nav {
    margin-top: 20px;
    
  }

  input[type="text"], input[type="password"], input[type="email"] {
  width: 100%;
  padding: 12px 16px;
  margin-top: 10px;
  margin-bottom: 20px;
  box-sizing: border-box;
  border: 1px solid #ccc;
  border-radius: 8px;
  font-size: 18px;
  line-height: 1.4;
  box-shadow: inset 0 1px 3px rgba(0,0,0,0.1);
}

label {
  display: block;
  font-weight: bold;
  
  margin-top: 10px;
}

.form-group {
  margin-bottom: 15px;
  text-align: left;
}

</style>


<div class="form-container">
  <div class="form-title">できたこと日記</div>
  <div class="message-container">
    {% if messages %}
      {% for message in messages %}
        <p>{{ message.message }}</p>
      {% endfor %}
    {% endif %}
   </div> 
    <form method="POST">    
      {% csrf_token %}
      <div class="form-group text-start mb-3">
        <label for="{{ login_form.email.id_for_label }}">メールアドレス</label>
        {{ login_form.email }}
        {% if login_form.email.errors %}
          <div class="text-danger">{{ login_form.email.errors }}</div>
        {% endif %}
      </div>

      <div class="form-group text-start mb-3">
        <label for="{{ login_form.password.id_for_label }}">パスワード</label>
        {{ login_form.password }}
        {% if login_form.password.errors %}
          <div class="text-danger">{{ regist_form.password.errors }}</div>
        {% endif %}
      </div>

    <input type="submit" value="ログイン" class="btn btn-primary">
    </form>    
    <nav>
     <a href="{% url 'diary_app:regist' %}">新規登録はこちら</a>
    </nav>  
</div>
</div>
{% endblock %}