diary/diary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary_app/',  include('diary_app.urls')),
    path('', include('diary_app.portfolio_urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/diary_app/urls.py
from django.urls import path
from .import views
from. views import ReflectionListView

app_name = 'diary_app'

urlpatterns = [
    # path('', views.portfolio, name='portfolio'),
    path('regist/', views.regist, name='regist'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('reflection/<int:year>/<int:month>/', ReflectionListView.as_view(), name='reflection'),
    path('my_page/', views.my_page, name='my_page'),
    path('change_password/', views.change_password, name='change_password'),
    path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    path('today_input/<int:year>/<int:month>/<int:day>/', views.today_input, name='today_input'),
    # path('diary_inspection/<int:year>/<int:month>/<int:day>/', DiaryInspectionListView.as_view(), name='diary_inspection'),
    path('edit_diary/<int:pk>/<int:year>/<int:month>/<int:day>/', views.edit_diary, name='edit_diary'),
    path('delete_diary/<int:pk>/<int:year>/<int:month>/<int:day>/', views.delete_diary, name='delete_diary'),
    path('edit_reflection/<int:year>/<int:month>/', views.edit_reflection, name='edit_reflection'),
    path('delete_reflection/<int:year>/<int:month>/', views.delete_reflection, name='delete_reflection'),
    
    
]

diary/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<style>

.btn-logout {
    background-color: #F08080;
    color: #FFFFFF;
    padding: 10px 25px;
    border-radius: 5px;
    border: 1px solid #ccc;
    font-size: 16px;
    
  }

.btn-logout:hover {
  background-color: #f19292ff;           
  transition: 0.2s ease;      
}

html {
  overflow-y: auto;            
  scrollbar-gutter: stable;
}

</style>    
    <head>
        <meta charset='utf-8'>
        <title>{% block title %}できたこと日記{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        {% block extra_css %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light .custom-navbar " style="position: fixed; top: 0; width: 100%; z-index: 1000; background-color: #7FFFD4;">
             <div class="container-fluid">
                <h3 class="mb-0 align-self-center">できたこと日記</h3>
                <a class="navbar-brand" href="{% url 'diary_app:month' year=today.year month=today.month %}">ホーム</a>
                {% comment %} <a class="navbar-brand" href="{% url 'diary_app:diary_inspection' year=today.year month=today.month  day=today.day %}">今日できたこと</a> {% endcomment %}
                <a class="navbar-brand" href="{% url 'diary_app:reflection' year=today.year month=today.month %}">1週間・1ヶ月の振り返り</a>
                <a class="navbar-brand" href="{% url 'diary_app:my_page'%}">マイページ</a>
                <form method="post" action="{% url 'diary_app:logout'%}">
                  {% csrf_token %}
                  <button type="submit" class="btn-logout">ログアウト</button>
                </form>
            </div>
        </nav>
           <div class="container" style="margin-top: 80px;">
            {% block content %}{% endblock %}
           </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>        

diary/templates/change_password.html
{% extends "base.html" %}
{% block content %}

<style>
.centered-form {
  max-width: 550px;
  margin: 0 auto;
  text-align: left;
}

label {
  display: block;
  font-weight: bold;
  margin-bottom: 10px;
}

.form-group {
  margin-bottom: 50px;

}

 .form-buttons {
  text-align: center;
  
}

.form-label {
  display: block;
  font-weight: bold;
  margin-bottom: 15px;
  margin-left: -220px;  
}  

.form-label-new{
  display: block;
  font-weight: bold;
  margin-bottom: 15px;
  margin-left: -170px;  
}  

input[type="submit"] {
  width: 60%;
  margin-top: 30px;
  margin-bottom: 30px;
}

.form-control {
  width: 100%;       /* 親要素いっぱいに */
  max-width: 330px;  /* 必要なら最大幅の制限 */
  margin: 0 auto;    /* 中央寄せ */
} 

textarea,
input[type="password"] {
  border: 1px solid #ccc;
  border-radius: 8px;
  font-size: 18px;
  line-height: 1.4;
  box-sizing: border-box;
  box-shadow: inset 0 1px 3px rgba(0,0,0,0.1);
  padding: 12px 16px;
}  
  
.mb-6 {
  margin-bottom: 3.5rem !important;  /* mt-5 より大きい値に調整 */
}


.input-area {
  max-width: 330px;   /* テキストボックスの幅に合わせる */
  margin: 0 auto;     /* ページ中央に配置 */
  text-align: left;   /* 左揃え */
}

ul.errorlist {
  margin-top: 4px;     
}

.container {
  padding-bottom: 50px;  
}


</style>

<h4>パスワード変更</h4> 
{% comment %} <div class="page-wrapper">  {% endcomment %}
  <div class="container"> 
      {% if messages %}
        <div class="text-center">
        {% for message in messages %}
          <p>{{ message.message }}</p>
        {% endfor %}
        </div> 
      {% endif %}
     
    <form method="POST" class="mt-5 centered-form">     
      {% csrf_token %}

      <div class="form-group text-center">
        {% comment %} <div class ="text-center"> {% endcomment %}
          <label for="{{ password_change_form.id_for_label }}" class="form-label">現在のパスワード</label>
        {% comment %} </div> {% endcomment %}
        <div class="input-area">
        {{ password_change_form.current_password }}
        {% if password_change_form.current_password.errors %}
           <div class="text-danger">{{ password_change_form.current_password.errors }}</div>
        {% endif %}
         </div>
      </div>

      <div class="form-group text-center">
        {% comment %} <div class ="text-center"> {% endcomment %}
          <label for="{{ password_change_form.id_for_label }}" class="form-label">新しいパスワード</label>
        {% comment %} </div> {% endcomment %}
        <div class="input-area">
        {{ password_change_form.password }}
        {% if password_change_form.password.errors %}
           <div class="text-danger">{{ password_change_form.password.errors }}</div>
        {% endif %}
        </div>
      </div>

      <div class="form-group text-center ">
        {% comment %} <div class ="text-center"> {% endcomment %}
          <label for="{{ password_change_form.id_for_label }}" class="form-label-new">新しいパスワード再入力</label>
        {% comment %} </div>   {% endcomment %}
        <div class="input-area">
        {{ password_change_form.confirm_password }}
        {% if password_change_form.confirm_password.errors %}
          <div class="text-danger">{{ password_change_form.confirm_password.errors }}</div>
        {% endif %}
        </div> 
      </div>
      
      <div class="form-buttons">
        <input type="submit" value="変更" class="btn btn-primary">
      </div>   
    </form>
    
    <div class="text-center">     
    <a href="{% url 'diary_app:my_page' %}">戻る</a>
    </div>
    
  </div>
{% comment %} </div> {% endcomment %}
{% endblock %}

diary/templates/delete_diary.html
{% comment %} <div class="modal fade" tabindex="-1" role="dialog" id="deleteModal-{{object.pk}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">データの削除</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>削除すると元に戻すことはできません。よろしいでしょうか？</p>
            </div>
            <div class="modal-footer">
              <form method="POST" action="{% url 'nippo-delete' object.pk %}">{% csrf_token %}
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-danger">DELETE</button>
              </form>
            </div>
        </div>
    </div>
</div> {% endcomment %}

diary/templates/home.html
{% extends "base.html" %}
{% load diary_extras %}
{% block content %}
<script>
  const todayServer = "{{ today|date:'Y-m-d' }}";
</script>

<style>


.triangle-left{
  width: 0;
  height: 0;
  border-top: 10px solid transparent;
  border-right: 10px solid black;
  border-bottom: 10px solid transparent;
  display: inline-block;
}

.triangle-right{
  width: 0;
  height: 0;
  border-left: 10px solid black;
  border-top: 10px solid transparent;
  border-bottom: 10px solid transparent;
  display: inline-block;
}

.triangle-link {
    display: inline-block;
    text-decoration: none;
}  

.calendar-table {
  width: 100%;
  table-layout: fixed; 
  border-collapse: collapse;
  margin-top: 5px;
  {% comment %} margin-bottom: 50px;   {% endcomment %}
}

.calendar-table td,
.calendar-table th {
  border: 1px solid #8d8c89e9;
  vertical-align: middle;
  height: 85px;
  max-height: 100px;
  font-size: 16px;
  
}

{% comment %} .calendar-table td,
.calendar-table th {
  height: 85px;
} {% endcomment %}

{% comment %} .calendar-table th {
  max-height: 100px;
  font-size: 16px;
} {% endcomment %}

.calendar-table th {
  background-color: #befafaff;
  font-weight: bold;
  text-align: center;
  padding: 5px;
  height: 60px;    
}

.calendar-table td {
  text-align: left;
  padding-left: 8px;
}

.bg-today {
  background-color: #AEFCE2FF;  
}

#future-modal {
  display: none;
  position: fixed;
  top: 30%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: #fff;
  border: 2px solid #aaa;
  border-radius: 15px;
  padding: 40px 60px;
  z-index: 9999;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
  text-align: center;
  font-size: 20px;
}

#future-modal p {
  margin-bottom: 30px;
}

#future-modal button {
  padding: 12px 30px;
  font-size: 18px;
  background-color: #8d8c89e9; 
  color: white;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
}

#future-modal button:hover {
  background-color: #c5c4c2e9;!important; 
  color: white;           
  transition: 0.2s ease;     
}


.goal-text {
  display: block;
  justify-content: space-between;
  align-items: center;
  font-size: 14px;
  margin-left: 30px;   
  max-width: 100%;            
  word-break: break-all;  
  overflow-wrap: anywhere; 
}  

.diary-link.other-month {
  color: #FFA07A !important;
  text-decoration: underline !important;
  text-decoration-color: #FFA07A !important;
  pointer-events: none; 
  cursor: default;
}

.container {
  padding-bottom: 50px;  
}

h4 {
  padding-top: 20px;
}





</style>

{% if user.is_authenticated %}
<div class="container">
<p style= "font-weight: bold; font-size: 16px; margin-bottom: 15px;">★今日自分ができたことを書いてみましょう</p>
    <div class="container  text-center">
      {% if messages %}
        {% for message in messages %}
        <p>{{ message.message}}</p>
        {% endfor %}
      {% endif %}  
      {% if streak >= 30 %}
        {% if streak == 30 %}
          <p style= "font-weight: bold; font-size: 20px; margin-bottom: 10px; color: #FF1493;">{{ streak }} 日連続！ついに1ヶ月達成🎉✨</p>
        {% else %}
          <p style= "font-weight: bold; font-size: 20px; margin-bottom: 10px; color: #FF69B4;">{{ streak }} 日連続！1ヶ月超えの大記録更新中🔥</p>
        {% endif %} 
      {% elif streak >= 20 %}  
        <p style= "font-weight: bold; font-size: 20px; margin-bottom: 10px; color:  #FF4500;">{{ streak }} 日連続！すごい根気👏</p>    
      {% elif streak >= 10 %}  
        <p style= "font-weight: bold; font-size: 20px; margin-bottom: 10px; color: #FF8C00;">{{ streak }} 日連続！習慣になってきたね👏</p>    
      {% elif streak >= 5 %}  
        <p style= "font-weight: bold; font-size: 20px; margin-bottom: 10px; color: #32CD32;">{{ streak }} 日連続！いいペースだよ😊</p>  
      {% elif streak >= 2 %}  
        <p style= "font-weight: bold; font-size: 20px; margin-bottom: 10px; color: #1E90FF;">{{ streak }} 日連続！その調子！</p>  
      {% endif %}
      <h4>
        <a href="{% url 'diary_app:month' month_previous.year month_previous.month %}"  class="triangle-link">
             <div class="triangle-left"></div>
        </a>
         {{ month_current | date:"Y年m月"}}
        
        <a href="{% url 'diary_app:month' month_next.year month_next.month %}" class="triangle-link">
             <div class="triangle-right"></div>
        </a>
      </h4>
        
    </div>

    <table class="calendar-table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week in month_days %}
            <tr>
                {% for day in week %}    
                  {% with date_str=day|date:"Y-m-d" %}  
                    {% if now == day and day in diary_dates %}
                      <td style="background-color:#FFA07A;">
                    {% elif day in diary_dates %}              
                      <td style="background-color:#FFDAB9;">
                    {% elif now == day %}
                      <td class="bg-today">      
                    {% else %}    
                      <td> 
                    {% endif %}
                    <div style="display: flex; flex-direction: column; height: 100%;">
                      <div style="text-align: left; font-weight: bold;">  
                        {% with diary_pk=diary_dict|get_item:date_str %}
                          {% comment %} {% if diary_pk %}
                            <a href="{% url 'diary_app:edit_diary' pk=diary_pk year=day.year month=day.month day=day.day %}" class="diary-link" data-date="{{ day|date:'Y-m-d' }}">
                            </a>  
                          {% else %}
                            <a href="{% url 'diary_app:today_input' year=day.year month=day.month day=day.day %}" class="diary-link" data-date="{{ day|date:'Y-m-d' }}">
                            </a>  
                          {% endif %}  {% endcomment %}
                          {% if month_current.month != day.month %}
                             <span style="color:#B0C4DE; ">
                              {{ day | date:"j" }}
                             </span> 
                          {% elif diary_pk %}
                            <a href="{% url 'diary_app:edit_diary' pk=diary_pk year=day.year month=day.month day=day.day %}" class="diary-link" data-date="{{ day|date:'Y-m-d' }}">
                            {{ day.day }} 
                            </a>
                          {% else %}
                            <a href="{% url 'diary_app:today_input' year=day.year month=day.month day=day.day %}" class="diary-link" data-date="{{ day|date:'Y-m-d' }}">
                            {{ day.day }}  
                            </a>    
                          {% endif %} 
                        {% endwith %}  
                     </div>      
                     {% with goal=tomorrow_goals_dict|get_item:date_str %}
                       {% if goal %}
                        <div class="goal-text">
                          <span> {{ goal|linebreaksbr|safe }}</span>
                        </div>
                       {% endif %}
                     {% endwith %}  
                   </div>   
                   </td>               
                  {% endwith %}     
                {% endfor %} 
            </tr>
        {% endfor %}
        </tbody>
    </table>
      
       
{% endif %}
</div> 


<div id="future-modal">
  <p>未来の日付にはまだ日記をつけられません </p>
  <button onclick="document.getElementById('future-modal').style.display='none'">OK</button>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const links = document.querySelectorAll('.diary-link');
    const today = todayServer;

    links.forEach(link => {
      const dateStr = link.dataset.date;
      if (!dateStr) return;

      link.addEventListener('click', function (event) {
        if (dateStr > today) {
          event.preventDefault();
          document.getElementById('future-modal').style.display = 'block';
        }
      });
    });
  });
</script>
{% endblock %}

diary/templates/portforlio.html
<h1>作品No.1できたこと日記</h1>

<p>できたこと日記は、今日1日で達成したことやできたことを毎日書くことで、ユーザーが自信や人生の充実感を得ることができるアプリです。
    このアプリを利用することで、ボタン式でその日にできたことを記録していくので、忙しい人でも毎日続けることができます。
    更に、明日の目標を書くスペースがあるので、目標達成できると感じることもできます。1週間・1か月でできたことを振り返る機能もあるため、
    自分の成長を実感できます。</p>
    
    <p>企画書</p> 
    <p>画面設計図</p> 
    <p>画面遷移図</p> 
    <p>ER図</p>

    <p>このアプリにアクセス</p>

diary/templates/reflection.html
{% extends "base.html" %}
{% block content %}

<style>
.triangle-left{
  width: 0;
  height: 0;
  border-top: 10px solid transparent;
  border-right: 10px solid black;
  border-bottom: 10px solid transparent;
  display: inline-block;
}

.triangle-right{
  width: 0;
  height: 0;
  border-left: 10px solid black;
  border-top: 10px solid transparent;
  border-bottom: 10px solid transparent;
  display: inline-block;
}

 .triangle-link {
    display: inline-block;
    text-decoration: none;
 }

 .table-container {
  
  
  max-height: 600px;
  margin-top: 20px;
}

table {
  width: 100%;
  min-width: auto;
  {% comment %} table-layout: auto; {% endcomment %}
  font-size: 14px;
  border-spacing: 0;
  table-layout: fixed; 
  
}

th, td {
  border: 1px solid #8d8c89e9;
  padding: 8px 12px;
  vertical-align: top;
  word-break: break-word;
  white-space: normal;
  overflow-wrap: break-word;
  line-height: 1.2;
  height: 80px;
  max-height: 80px;
  
}


thead th {
    vertical-align: middle;
    {% comment %} background-color: rgb(190, 250, 250); {% endcomment %}
    font-weight: bold;
    text-align: center;
    padding: 5px;
    height: 60px;
    font-size: 16px;
    position: sticky;
    top: 0;
    {% comment %} z-index: 1; {% endcomment %}
    background: none;
    border-top: none;
    border-bottom: none;
    {% comment %} border: 1px solid #8d8c89e9; {% endcomment %}
}

thead th::before {
    content: "";
    width: 100%;
    height: 100%;
    {% comment %} display: block; {% endcomment %}
    {% comment %} border: 1px solid #8d8c89e9; {% endcomment %}
    position: absolute;
    top: 0px;
    left: 0px;
    box-sizing: content-box;
    z-index: -1;
    border-top: 1px solid #8d8c89e9;
    border-bottom: 1px solid #8d8c89e9;
    background-color: #befafaff;
  }




.col-1 { width: 8%; }
.col-2 { width: 8%; }
.col-3 { width: 8%; }
.col-4 { width: 8%; }
.col-5 { width: 8%; }
.col-6 { width: 8%; }
.col-7 { width: 8%; }
.col-8 { width: 14%; }
.col-9 { width: 14%; }
.col-10 { width: 16%; }



{% comment %} .th:before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border-top: 1px solid #8d8c89e9;
  border-bottom: 1px solid #8d8c89e9;
  background: #befafaff;
  z-index: -1;
} {% endcomment %}


th:first-child {
  background-color: rgb(190, 250, 250); /* 1列目も背景を固定 */
  position: sticky;
  top: 0px;
  /* ヘッダーより上にする */
}

td {
    max-height: 100px;
    background-color: #ffffff;
    border: 1px solid #8d8c89e9;
  

}

.navigation h5 {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
}

.container.text-center h5 {
  margin-top: 10px;
  margin-bottom: 10px;
}

.button-group {
  margin-top: 20px;
  margin-bottom: 20px;
}


p {
    margin-top: 20px;
    margin-bottom: 30px;
  }

h5{
    margin-top: 20px;
}

.btn  {
  min-width: 100px;
  gap: 10px;
  padding: 10px 25px;
  font-size: 1.2rem;
  border-radius: 5px;
  border: 1px solid #ccc;
}

.btn-input-edit{
  background-color: #007bff;
  color: white;
}

.btn-input-edit:hover{
  background-color: #449cfbff;
  color: white;
  transition: 0.2s ease;
}

.btn-cancel {
  background-color: #b4b4b4ff;
  color: #333;
}

.btn-cancel:hover {
  background-color: #c7c7c7ff;
  color: #333;
  transition: 0.2s ease;
}

.btn-cancel-modal{
  background-color: #b4b4b4ff;
  padding: 10px 25px;
  color: #333;
}

.btn-cancel-modal:hover {
  background-color: #c7c7c7ff;
  color: #333;
  transition: 0.2s ease;
}


.btn-delete {

  background-color: #c82333;
  padding: 15px 55px;
  color: white;
}

.btn-delete:hover  {
  background-color: #dc3545;
  color: white;
  transition: 0.2s ease;
}

.btn-delete-modal{
  background-color: #c82333;
  padding: 10px 38px;
  color: white;
}

.btn-delete-modal:hover {
  background-color: #dc3545;
  color: white;
  transition: 0.2s ease;
}

#emptyModal button {
  padding: 12px 30px;
  font-size: 18px;
  background-color: #8d8c89e9;
  color: white;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);

}

#emptyModal button:hover {
  background-color: #c5c4c2e9;!important;
  color: white;
  transition: 0.2s ease;
}

.container-bottom-space {
  padding-bottom: 50px;
}


</style>

<h4>{{ year }}年{{ month }}月の振り返り</h4>

<div class="container container-bottom-space">
  <div class="container  text-center">
  {% if messages %}
    {% for message in messages %}
    <p>{{ message.message}}</p>
    {% endfor %}
  {% endif %}
  </div>

  <div class="navigation">
    <h5>
        <a href="{% url 'diary_app:reflection' month_previous.year month_previous.month %}"  class="triangle-link">
             <div class="triangle-left"></div>
        </a>
         {{ month_current | date:"Y年m月"}}

        <a href="{% url 'diary_app:reflection' month_next.year month_next.month %}" class="triangle-link">
             <div class="triangle-right"></div>
        </a>
      </h5>
  </div>


<h5>1週間ごとの振り返り</h5>
<div class="d-flex justify-content-end mb-2">
  <button type="button" class="btn btn- btn btn-input-edit"
        onclick="location.href='{% url 'diary_app:edit_reflection' year=year month=month %}'">
    振り返りを入力・編集
  </button>
</div>
<div class="table-container">
<table>
    {% comment %} <colgroup>
    <col span="7" style="width: 7%;">
    <col style="width: 10%;">
    <col style="width: 10%;">
    <col style="width: 10%;">
    </colgroup> {% endcomment %}
    <thead>
        <tr>
          <th class="col-1">月</th>
          <th class="col-2">火</th>
          <th class="col-3">水</th>
          <th class="col-4">木</th>
          <th class="col-5">金</th>
          <th class="col-6">土</th>
          <th class="col-7">日</th>
          <th class="col-8">今週のハイライト</th>
          <th class="col-9">できた理由</th>
          <th class="col-10">今後はどのような<br>工夫をしたらよいか</th>
        </tr>
    </thead>
    <tbody>
         {% for week_num, data in weeks.items %}
          <tr>
              {% for day,diary in data.days_diaries %}
                  <td>
                    {% if month_current.month != day.month %}
                      <div style= "font-size:14px; color:#B0C4DE; margin-bottom:5px;font-weight: bold; ">{{ day.day }}</div>
                    {% else %}
                      <div style= "font-size:14px; color:#0000EE; margin-bottom:5px; font-weight: bold;">{{ day.day }}</div>
                    {% endif %}
                    {% if diary %}
                      {% for success in diary.success_list %}
                        <span style="white-space: nowrap;">・{{ success.label|slice:":1" }}</span>{{ success.label|slice:"1:" }}<br>
                      {% endfor %}
                    {% endif %}
                  </td>
              {% endfor %}
               <td>{{ data.reflection.highlight|default_if_none:""|linebreaksbr }}</td>
               <td>{{ data.reflection.reason|default_if_none:""|linebreaksbr }}</td>
               <td>{{ data.reflection.next_plan|default_if_none:""|linebreaksbr }}</td>
          </tr>
          {% endfor %}
    </tbody>
</table>
</div>
<h5>今月の振り返り</h5>
  <div style="margin-top: 30px;">
      <p><strong>■各週のハイライトに共通する点</strong><br>
      {% if month_reflection and month_reflection.common_ground %}
        <p>{{ month_reflection.common_ground|default_if_none:""|linebreaksbr }}</p>
      {% else %}
        <p>まだ記入されていません。</p>
      {% endif %}
      <p><strong>■自分の価値観や大切にしていること</strong><br>
      {% if month_reflection and month_reflection.my_values  %}
        <p>{{ month_reflection.my_values|default_if_none:""|linebreaksbr }}</p>
      {% else %}
        <p>まだ記入されていません。</p>
      {% endif %}
      <p><strong>■その他気づいたこと</strong><br>
      {% if month_reflection and month_reflection.awareness %}
        <p>{{ month_reflection.awareness|default_if_none:""|linebreaksbr }}</p>
      {% else %}
        <p>まだ記入されていません。</p>
      {% endif %}
  </div>

  <div class="button-group">
  {% if month_reflection or  data.reflection %}
    <button type="button" class="btn btn-delete" data-bs-toggle="modal" data-bs-target="#deleteModal-{{diary.id}}">
      削除
    </button>
  {% else %}
    <button type="button" class="btn btn-delete" data-bs-toggle="modal" data-bs-target="#emptyModal">
      削除
    </button>
  {% endif %}
  </div>
</div>

          <div class="modal fade" tabindex="-1" role="dialog" id="deleteModal-{{diary.id}}">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">1週間・1ヶ月の振り返りを削除</h5>
                </div>
                <div class="modal-body">
                  <p>削除すると元に戻すことはできません。削除してもよろしいでしょうか？</p>
                </div>
                <div class="modal-footer">
                  <form method="POST" action="{% url 'diary_app:delete_reflection' year=year month=month %}">
                    {% csrf_token %}
                    <button type="button" class="btn btn-cancel-modal" data-bs-dismiss="modal">キャンセル</button>
                    <button type="submit" class="btn btn-delete-modal">削除</button>
                  </form>
                </div>
              </div>
            </div>
          </div>

          <div class="modal fade" tabindex="-1" role="dialog" id="emptyModal">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">まだ記録がありません</h5>
                </div>
                <div class="modal-body">
                  <p>この日の記録はまだありません。削除する内容がありません。</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
                </div>
              </div>
            </div>
          </div>


{% endblock %}